apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aks-dropwizard-ingress
  namespace: dropwizard
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /hello-world
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: aks-dropwizard
          servicePort: 80
