apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: acs-dropwizard-{{.Release.Name}}
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: acs-dropwizard-{{.Release.Name}}
    spec:
      containers:
      - name: acs-dropwizard-{{.Release.Name}}
        image: pratham98k/dropwizard:1.1
        ports:
        - containerPort: 8080
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: acs-dropwizard-{{.Release.Name}}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-dropwizard-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: acs-dropwizard-{{.Release.Name}}
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
